spring.application.name=detector-trampas
server.port=${PORT:8080}


anthropic.api.key=tu-api-key-aqui

# Opción 2: variable de entorno (recomendado para producción)

# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8

# Logging
logging.level.com.detectortrampas=DEBUG
